### ISSUE TITLE
default conflict resolver delete wins is not working 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#433]
Steps to reproduce : 
1. Create docs in CBL.
        2. Replicate docs to SG with push_pull and continuous true
        3. Wait until replication is idle
        4. Stop the replication 
        5. Update doc in Sg.
        6. Delete doc in CBL. -> Verify no docs existed in CBL DB. 
        7. Start replication with push_pull and continuous true
    
Result : Docs in sync-gateway got replicated to CBL and I can see docs in both SG and CBL.
Expected : Docs should get deleted in both SG and CBL as delete should win with conflict

cbl logs : https://gist.github.com/sridevi-15/f4a38dd29c5269cf49ace6adabf50507

**Comment by snej** [comment]
I don't understand the Result and Expected. Are they reversed? Can you give more details?

Also, I'm curious why all of the tests seem to run continuous replications, even when the desired effect is one-shot (as in this test.) Do you have equivalent tests that run one-shot replications too?

**Comment by sridevi-15** [comment]
@snej , I ran with one shot replication and I see same behavior. I modified result and Expected, sorry it was confusing i guess.

**Comment by sridevi-15** [comment]
Here is the pytest : https://github.com/couchbaselabs/mobile-testkit/blob/869c9daf7a79e35a6d64ba57207ef2909861d14e/testsuites/CBLTester/CBL_Functional_tests/test_replication.py#L1314
 Test name is : test_default_conflict_scenario_delete_wins

You can comment on all parameters, have just one parameter and run.

**Comment by borrrden** [comment]
This is an issue stemming from back when deletes always lost.  To determine if there was a conflict when pulling, the puller will run a combination of `c4doc_selectCurrentRevision` and `c4doc_selectNextLeafRevision` with a flag to ignore deletes.  As such, it doesn't consider the document conflicted since the inserted revision was a deletion and doesn't call back to ask Couchbase Lite what to do.

I tried to reason what should be done here but everything seems very delicate and deep into the paradigm that deletes should lose.  My first intuition is to change the `compareRevs` function somehow because it will pick non-deletions over deletions as winners.  @snej Hope that this information is helpful.

**Comment by borrrden** [comment]
Oh and note for @sridevi-15 The test has some incorrect assumptions.  Particularly this:

```python
    if delete_source == 'sg':
        sg_client.delete_docs(url=sg_url, db=sg_db, docs=sg_docs, auth=session)
        db.update_bulk_docs(cbl_db, number_of_updates=number_of_updates)
```

This will delete the docs on Sync Gateway while updating them on CBL if the delete source is set to SG as it is in the first variation, but then immediately after there is this:

```python
cbl_doc_ids = db.getDocIds(cbl_db)
cbl_docs = db.getDocuments(cbl_db, cbl_doc_ids)
assert len(cbl_docs) == 0, "did not delete docs after delete operation"
```

This will never be true, because the replication doesn't start until after this line.  This also needs to be guarded with the delete source check.

**Comment by borrrden** [comment]
Reading this over again I feel like I should be more clear.  Here is the flow:

1. Get into a consistent state with a document on CBL and SG (identical rev tree)
2. Stop all replication
3. Update on CBL, and delete on SG
4. Start replication again
5. The puller will receive the revision, and call to DBWorker to insert it.  DBWorker will do so, and then check for a conflict by querying "more than one non-deleted leaf revision."  Since this is not true, no conflict will be reported and the updated version on CBL will remain the "current" one.

**Comment by sridevi-15** [comment]
@borrrden , that is what I have done. At steps 3 if delete_souce==sg, it will deleted doc in SG , update same doc in CBL . Then it start replication again and wait until replication is idle. It verified that docs got removed in CBL and SG.

**Comment by snej** [comment]
Should be fixed now. We should also add a unit test for this situation, both to LiteCore and to CBL.

**Comment by pasin** [comment]
I wrote CBL unit tests and tested them with the updated LC. I could still see the issue.

1. local doc after delete:
```
(cblite) revs doc1
Document "doc1", current revID 2-8f5b7bdd81473bb44faa5a6dda003fa9028a0eac, sequence #2, Deleted
* 1-5b90fd1948276c02d409967a87339b1517e0c0b6 (#1)
  * 2-8f5b7bdd81473bb44faa5a6dda003fa9028a0eac (#2), 2 bytes, Deleted, Leaf
```

2. Remote doc:
```
digraph graphname{"1-5b90fd1948276c02d409967a87339b1517e0c0b6" -> "2-9ae47ef0b2ad600a22f127bd9ef8631b"; }
```

3. Running a pull replicator to pull the remote doc. After finish replicating, here is the rev-tree:
```
Document "doc1", current revID 2-9ae47ef0b2ad600a22f127bd9ef8631b, sequence #3
* 1-5b90fd1948276c02d409967a87339b1517e0c0b6 (#1)
  * 2-9ae47ef0b2ad600a22f127bd9ef8631b (#3), 12 bytes, Leaf, KeepBody
  * 2-8f5b7bdd81473bb44faa5a6dda003fa9028a0eac (#2), 2 bytes, Deleted, Leaf
```

 In this step, I could see that the conflict resolver in CBL is called but the conflict resolver failed as the selectConflictingRevision method  returned false in this [line](https://github.com/couchbase/couchbase-lite-ios/blob/master/Objective-C/CBLDatabase.mm#L918-L919). Below is the CBL log.

```
2018-03-02 20:59:01.148420-0800 xctest[69238:2617797] CouchbaseLite Sync Verbose: {IncomingRev#7}==> litecore::repl::IncomingRev ->ws:localhost:4984/scratch/_blipsync
2018-03-02 20:59:01.148737-0800 xctest[69238:2617793] CouchbaseLite Sync Info: {Pull#6} Caught up with remote changes
2018-03-02 20:59:01.149141-0800 xctest[69238:2617797] CouchbaseLite Sync Verbose: {IncomingRev#7} Received revision 'doc1' #2-9ae47ef0b2ad600a22f127bd9ef8631b (seq '3')
2018-03-02 20:59:01.201989-0800 xctest[69238:2617793] CouchbaseLite Sync Verbose: {DBWorker#5} Inserting 1 revs:
2018-03-02 20:59:01.202764-0800 xctest[69238:2617793] CouchbaseLite Sync Verbose: {DBWorker#5}     {'doc1' #2-9ae47ef0b2ad600a22f127bd9ef8631b}
2018-03-02 20:59:01.204054-0800 xctest[69238:2617793] CouchbaseLite Sync Info: {DBWorker#5} Created conflict with 'doc1' #2-9ae47ef0b2ad600a22f127bd9ef8631b
2018-03-02 20:59:01.204775-0800 xctest[69238:2617793] CouchbaseLite Sync Info: {DBWorker#5} Inserted 1 revs in 2.32ms (432/sec)
2018-03-02 20:59:01.205063-0800 xctest[69238:2617794] CouchbaseLite Sync Verbose: {Pull#6} Checkpoint now at 3
2018-03-02 20:59:01.205381-0800 xctest[69238:2616178] CouchbaseLite Sync Info: CBLReplicator[<- URL[ws://localhost:4984/scratch]]: pulled conflicting version of 'doc1'
2018-03-02 20:59:01.205916-0800 xctest[69238:2617794] CouchbaseLite Sync Verbose: {Pull#6} progress +1/+0, 1 docs -- now 1 / 1, 1 docs
2018-03-02 20:59:01.206679-0800 xctest[69238:2617794] CouchbaseLite Sync Verbose: {Pull#6} now stopped
2018-03-02 20:59:01.206917-0800 xctest[69238:2617793] CouchbaseLite Sync Verbose: {Repl#4} progress +1/+0, 1 docs -- now 1 / 1, 1 docs
2018-03-02 20:59:01.207242-0800 xctest[69238:2616178] CouchbaseLite Sync WARNING: CBLReplicator[<- URL[ws://localhost:4984/scratch]]: Conflict resolution of 'doc1' failed: (null)
2018-03-02 20:59:01.207765-0800 xctest[69238:2617793] CouchbaseLite Sync Info: {Repl#4} Saving remote checkpoint cp-B0n24jd8XkJ2s04ECNPsmXBQBi4= with rev='0-1': {"local":1,"remote":3} ...
2018-03-02 20:59:01.209087-0800 xctest[69238:2616236] CouchbaseLite Sync Info: {Repl#4} Successfully saved remote checkpoint cp-B0n24jd8XkJ2s04ECNPsmXBQBi4= as rev='0-2'
2018-03-02 20:59:01.210026-0800 xctest[69238:2616232] CouchbaseLite Sync Info: {DBWorker#5} Saved local checkpoint cp-B0n24jd8XkJ2s04ECNPsmXBQBi4= to db
2018-03-02 20:59:01.355634-0800 xctest[69238:2616236] CouchbaseLite Sync Info: {Repl#4} Replication complete! Closing connection
```

4. With the rev-tree structure in Step 3, calling `[db documentWithID: @"doc1"]` return the document with the body from rev `2-9ae47ef0b2ad600a22f127bd9ef8631b` which is pulled from SG.

Unit Tests:
1. https://github.com/couchbase/couchbase-lite-ios/blob/master/Objective-C/Tests/ReplicatorTest.m#L853
2. https://github.com/couchbase/couchbase-lite-ios/blob/master/Objective-C/Tests/ReplicatorTest.m#L425

**Comment by borrrden** [comment]
I wonder if this would work:

Change the logic of select conflicting revision to loop through the next leaf revision until one is found with the conflicted flag.  

```
if(!_c4Doc) {
    return NO;
}

BOOL foundConflict = NO;
while(!foundConflict && c4doc_selectNextLeafRevision(_c4Doc.rawDoc, true, true, nullptr)) {
    foundConflict = (_c4Doc.selectedRev.flags & kRevIsConflict) != 0;
}

if(foundConflict) {
    self.c4Doc = _c4Doc;     // This will update to the selected revision
}

return foundConflict;
```

**Comment by borrrden** [comment]
The problem with the current implementation is that it follows the old way of checking for conflicts that Jens was forced to just change.

**Comment by borrrden** [comment]
@sridevi-15 Are those changes on the cbl20-ver1 branch?  Because I see this:

Replication is stopped [here](https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_replication.py#L1357)

Document count is checked [here](https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_replication.py#L1374)

There are no replications in between right?

**Comment by borrrden** [comment]
@pasin I confirmed the above logic works but the next problem is that the resolveConflict method is flawed.  The document isDeleted property will return true only if the **document** is deleted, not the selected revision.  Since this is now an internal property, the simplest thing to do is to just check the current revision instead of the document when determining deleted status.

**Comment by pasin** [comment]
@borrrden the logic above doesn't work when I tested as somehow both `2-9ae47ef0b2ad600a22f127bd9ef8631b` and `2-8f5b7bdd81473bb44faa5a6dda003fa9028a0eac` are not a conflicted revision. 

I don't know the logic to mark the revision as a conflicted revision. If the local revision is a deleted revision, will the remote revision be marked as a conflicted revision when it is inserted to the db?

**Comment by borrrden** [comment]
Hmmm that's weird.  I thought that whenever a callback to CBL occurred it was because the last inserted revision was marked with the conflicted flag.  I'll check your scenario (I was working on the other side, delete from SG)

**Comment by borrrden** [comment]
Ok yeah I see the same thing.  There is a callback for 409, but neither revision is marked as conflicted.  The weird part is that in LiteCore, it *is* marked as a conflict.  I don't know why it gets lost between the DBWorker portion and when it comes to CBL.  @snej Will need to shed some light there.

**Comment by borrrden** [comment]
It seems that the conflict flag get set for the document returned from `c4doc_put` contains the flag, but that is added and not actually saved?  Then LiteCore passes the docID to CBL and CBL uses `c4doc_get` and receives revisions without the flag.

**Comment by borrrden** [comment]
I found the culprit.  `RevTree::checkForResolvedConflict()` is clearing the flag if the current revision and no others are marked as conflicted (which is what happens during this scenario).  I think that LiteCore needs to make fewer assumptions about what to do with the rev tree at this point, and simply leave everything up to CBL.

**Comment by snej** [comment]
I've written LiteCore unit tests for both scenarios: update locally & delete on server, and delete locally & update on server. The first one passes (despite what Jim said on 3/1; maybe something's changed?) but the second does fail.

**Comment by borrrden** [comment]
LiteCore tests don't tell the whole story (CBL needs to also have these conflicts available in a reliable way during conflict resolution).  There was a change in behavior to handle the first one (which needed a corresponding CBL change) but the second one still has issues as you noted.

**Comment by snej** [comment]
I've fixed most of the problem in LiteCore, but (a) some of the bugs were in CBL-iOS, and (b) unfortunately I had to add a parameter to `c4doc_resolveConflict()` so all clients will have to make changes.

* RevTree sort logic changed so deleted local (non-conflict) revs come before live conflicting revs.
* c4doc_resolveConflict marks the winning revision/branch as non-conflict, and the losing branch as conflict.
* Added `mergedFlags` param to c4doc_resolveConflict, so that a merge revision can be a deletion.
* Added unit tests for pulling conflicts where one of the conflicting revs is a deletion.

**Comment by borrrden** [comment]
With the latest LiteCore I can confirm that all 6 test variations pass assuming one change in the test (more on that in a minute).  Out of this comes 1 question, and 1 confusing behavior.

1. The losing document tree is marked as "conflict" which is the same marker that a conflict gets when it comes in.  What is the correct way to select the *currently conflicted* revision of a document so that Couchbase Lite can properly resolve the document if it becomes conflicted again.  Is looping over the leafs until the first conflict sufficient?

2. The confusing behavior is that while a one-shot replication will resolve all the conflicts locally, it will not push the resolution back up to Sync Gateway (which is why the test requires a *continuous replication* after the conflict is introduced in order for it to pass).  This is because it will reach the end of the changes before the conflicts get resolved and saved and that will be the end of it.

**Comment by borrrden** [comment]
@pasin The logic I mentioned before should now work properly

@sridevi-15 To get the test to pass, change the replication that occurs after the simultaneous update / delete in the test to be continuous (or, possibly, run two one-shot replications)

@snej I suppose the above only applies to push/pull replication (a push only will simply skip the conflicts when it receives 409, and a pull only will have the same behavior as push/pull has now except that it is expected).  Might it be a good idea to mark a one-shot push/pull replication that received a conflict during its operation to send one more time instead of stopping as usual?

**Comment by snej** [comment]
@borrrden --

1. Hm, good point! I decided to mark all non-current branches with `kRevConflict`, but that does get in the way of distinguishing the new conflict. I could make `c4doc_resolveConflicts` not mark the losing branch, since it's deleted anyway. Its tombstone revision would come before revs marked as conflicts, though, so to find the conflict you'd have to iterate over the revisions looking for the first marked with `kRevConflict` and `kRevLeaf`.
2. Yeah, we could add some state to the replicator to remember revs that need to be re-pushed after catching up. I think the tricky part is detecting that CBL has resolved the conflict, since (a) how do you tell it apart from some other edit of the document, and (b) a one-shot replicator isn't listening for db changes, so it might have to add a doc-change observer for each doc that it marks as a conflict. Definitely post-2.0 :)

**Comment by borrrden** [comment]
Ok, so to summarize:  CBL needs to look for the first leaf revision marked as conflict when searching?  Since we iterate using "next leaf revision" I assume we don't have to check the leaf flag manually and just check the conflict flag?

**Comment by snej** [comment]
Yes, I checked what iOS is doing and it's correct. It calls `c4doc_nextLeafRevision` with the `deletions` flag off. So any other leaf it finds will be a conflict.

**Comment by borrrden** [comment]
I'm not sure it has to listen for db changes.  Would it be wrong just to run the entire process again?  For example if sequence 21 caused conflict sequence 31, and the pusher stopped at 30, and the pusher ran again and pushed 31 - 40 (which happened to be the current sequence number at the time it "restarted")?

**Comment by sridevi-15** [comment]
Is this bug fixed ? I tested on ios build -387 and android build -387 and I still see this issue.

**Comment by borrrden** [comment]
According to today's update, the builds should be iOS 687 and Android 397

**Comment by borrrden** [comment]
Actually there is a new issue after removing the `kRevConflict` flag that makes the library get the incorrect current revision if the current revision is a deletion.  Here is the way it goes down.  @snej I think there needs to be a separate flag to distinguish conflict losers.

After the resolution of a conflict involving a server side delete, the losing tree actually becomes longer than the winning tree:

```
* 1-9cbac6085bd2ff362e7dacbcbf483dabc8019794 (#9), 1578 bytes, KeepBody
  * 2-9399fafd5c59b58095911e99bc676002 (#22), 2 bytes, Deleted, Leaf, KeepBody
  * 2-5dee0d3ff64424712d21acfc11d79077cb343d03 (#19)
    * 3-d0f54ee0868778b6e21a888e43f052dc2692f593 (#32), 2 bytes, Deleted, Leaf
```

Here the server delete was 2-9399, and the client side update was 2-5dee.  The loser was deleted with a generation 3, making it "current".  This won't really matter until the next step:

Now the document is updated again:

```
* 1-9cbac6085bd2ff362e7dacbcbf483dabc8019794 (#9), 1578 bytes, KeepBody
  * 2-9399fafd5c59b58095911e99bc676002 (#22), 2 bytes, Deleted, Leaf, KeepBody
  * 2-5dee0d3ff64424712d21acfc11d79077cb343d03 (#19)
    * 3-d0f54ee0868778b6e21a888e43f052dc2692f593 (#32), Deleted
      * 4-f18df1f127c75c3b67ea84a38422f564da987608 (#49), 1582 bytes, Leaf
```

Suddenly it is on the wrong tree!  This causes SG to reject it and the test to fail because things on SG are still deleted.

**Comment by borrrden** [comment]
P.S. It looks like this final step of the test (resurrected the deleted doc) is new since I last tried it (commit 44582ae992e0cb29b20e3470729871a1c68f839e in mobile-testkit)

**Comment by raghusarangapani** [comment]
Tested it out with server 5.1.0-5552, sync-gateway 2.0.0-821 and CBL .net UWP 2.0.0-b0611:
All test_default_conflict_scenario_delete_wins parametrized tests fail. Assigning to @snej

**Comment by snej** [comment]
> I think there needs to be a separate flag to distinguish conflict losers.

I think so too. They're not the same thing as regular deletions, and this is biting us now.

**Comment by borrrden** [comment]
@snej Any CBL changes needed?

**Comment by snej** [comment]
Nope, it's all in LiteCore. (I modified the behavior of `c4doc_resolveConflict`, basically, and also the sorting priority of revisions.)

**Comment by sridevi-15** [comment]
I tested it out on beta2 builds  and still failing , both on android and iOS

**Comment by snej** [comment]
That's because the LiteCore submodule hadn't been updated in CBL-iOS. I just updated it now.

**Comment by sridevi-15** [comment]
@borrrden , This test has continuous false (one shot replication). Are you saying to changing to true?

**Comment by borrrden** [comment]
Yes, please read [this comment](https://github.com/couchbase/couchbase-lite-core/issues/433#issuecomment-370660472)

Also I still notice that the test has not been corrected as in [this comment](https://github.com/couchbase/couchbase-lite-core/issues/433#issuecomment-369491398)

In summary, currently line 1396 will never succeed if the delete source is 'sg' because the replicator is stopped on line 1367.  That means that the documents are deleted on Sync Gateway, but then checked on CBL without replication.  If you remove this line, and change 1397 to continuous the test passes for me.

**Comment by borrrden** [comment]
Sorry those line numbers are stale.  The lines are [here](https://github.com/couchbaselabs/mobile-testkit/blob/f5849b94626e3d0f0d70673f65c106c96d3a37a3/testsuites/CBLTester/CBL_Functional_tests/test_replication.py#L1360) and [here](https://github.com/couchbaselabs/mobile-testkit/blob/f5849b94626e3d0f0d70673f65c106c96d3a37a3/testsuites/CBLTester/CBL_Functional_tests/test_replication.py#L1388-L1389)

**Comment by borrrden** [comment]
The test passes for me with .NET as is right now (.NET build 629)

**Comment by borrrden** [comment]
iOS seems to have not picked up the change I mentioned above (and neither did Android) so I will assign @hideki and @snej (volunteered).  Once your platform is updated, you can remove yourself.  If you get a new build, the last person should put verify back and assign Sridevi.

**Comment by hideki** [comment]
@sridevi-15 ,

I ported `Document. selectConflictingRevision()` method fix from .NET implementation.
Could you please verify the fix with build 2.0.0-424 (the build is in progress.) or later?
http://mobile.maven.couchbase.com/feeds/dev//com/couchbase/lite/couchbase-lite-android-ee/2.0.0-424

Thanks!

**Comment by sridevi-15** [comment]
work fine now , tested on ios build 702

**Comment by sridevi-15** [comment]
sorry need to reopen the issue. I ran the test on android -427 build and I see issue on android. Ran couple of times with cc mode and still failing.

**Comment by hideki** [comment]
@borrrden  Could you please review review Java's `selectConflictingRevision()` method implementation? I wonder if lite-core throws exception rather than error code is `0`.
https://github.com/couchbase/couchbase-lite-android/blob/master/shared/src/main/java/com/couchbase/lite/Document.java#L497-L517

**Comment by hideki** [comment]
@sridevi-15 I don't have the reproducible environment, Could you please help me to set up the functional test environment on my development machine?

**Comment by hideki** [comment]
@sridevi-15 

CBL Android Build 2.0.0-435 includes the fix for this issue. I tested with the functional test.  This build should work fine. Please verify the fix. Thanks! 
http://mobile.maven.couchbase.com/feeds/dev//com/couchbase/lite/couchbase-lite-android-ee/2.0.0-435

**Comment by sridevi-15** [comment]
Verified on Android build 435 and works fine
