### ISSUE TITLE
Replicator races causes crashing

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#93]
Example:  Windows sometimes crashes at LoopbackProvider.hh:71 because `_peer` is `nullptr`.  Checking for null here causes Replication tests to hang waiting for replication to complete.

Ubuntu consistently crashes with this backtrace (it looks like the mailbox being enqueued to is null)

> tid = 8490, 0x00000000005dff6f CppTests`litecore::ThreadedMailbox::enqueue(this=0x0000000000000010, f=function<void ()> @ 0x00007ffff5bedd10)>) + 15 at Actor.cc:228, name = 'CppTests', stop reason = signal SIGSEGV: invalid address (fault address: 0xa0) 
    frame #0: 0x00000000005dff6f CppTests`litecore::ThreadedMailbox::enqueue(this=0x0000000000000010, f=function<void ()> @ 0x00007ffff5bedd10)>) + 15 at Actor.cc:228 [opt]
    frame #1: 0x0000000000596862 CppTests`litecore::repl::Replicator::_onClose(litecore::websocket::CloseStatus) [inlined] void litecore::Actor::enqueue<litecore::repl::Worker>(void (litecore::repl::Worker::*)()) + 53 at Actor.hh:200 [opt]
    frame #2: 0x000000000059682d CppTests`litecore::repl::Replicator::_onClose(litecore::websocket::CloseStatus) [inlined] litecore::repl::Worker::connectionClosed(this=<unavailable>) at Worker.hh:68 [opt]
    frame #3: 0x000000000059682d CppTests`litecore::repl::Replicator::_onClose(this=0x00000000009a6d30, status=litecore::blip::Connection::CloseStatus @ 0x00007ffff5beddd8) + 77 at Replicator.cc:185 [opt]
    frame #4: 0x00000000005991ed CppTests`void std::__1::__invoke_void_return_wrapper<void>::__call<std::__1::__bind<void (litecore::repl::Replicator::*&)(litecore::websocket::CloseStatus), litecore::repl::Replicator*, litecore::websocket::CloseStatus&>&>(std::__1::__bind<void (litecore::repl::Replicator::*&)(litecore::websocket::CloseStatus), litecore::repl::Replicator*, litecore::websocket::CloseStatus&>&) [inlined] _ZNSt3__18__invokeIRMN8litecore4repl10ReplicatorEFvNS1_9websocket11CloseStatusEERPS3_JRS5_EvEEDTcldsdeclsr3std3__1E7forwardIT0_Efp0_Efp_spclsr3std3__1E7forwardIT1_Efp1_EEEOT_OSC_DpOSD_ + 65 at __functional_base:382 [opt]
    frame #5: 0x00000000005991ac CppTests`void std::__1::__invoke_void_return_wrapper<void>::__call<std::__1::__bind<void (litecore::repl::Replicator::*&)(litecore::websocket::CloseStatus), litecore::repl::Replicator*, litecore::websocket::CloseStatus&>&>(std::__1::__bind<void (litecore::repl::Replicator::*&)(litecore::websocket::CloseStatus), litecore::repl::Replicator*, litecore::websocket::CloseStatus&>&) [inlined] _ZNSt3__115__apply_functorIMN8litecore4repl10ReplicatorEFvNS1_9websocket11CloseStatusEENS_5tupleIJPS3_S5_EEEJLm0ELm1EENS8_IJEEEEENS_13__bind_returnIT_T0_T2_Xsr22__is_valid_bind_returnISD_SE_SF_EE5valueEE4typeERSD_RSE_NS_15__tuple_indicesIJXspT1_EEEEOSF_ at functional:2056 [opt]
    frame #6: 0x00000000005991ac CppTests`void std::__1::__invoke_void_return_wrapper<void>::__call<std::__1::__bind<void (litecore::repl::Replicator::*&)(litecore::websocket::CloseStatus), litecore::repl::Replicator*, litecore::websocket::CloseStatus&>&>(std::__1::__bind<void (litecore::repl::Replicator::*&)(litecore::websocket::CloseStatus), litecore::repl::Replicator*, litecore::websocket::CloseStatus&>&) [inlined] _ZNSt3__16__bindIRMN8litecore4repl10ReplicatorEFvNS1_9websocket11CloseStatusEEJPS3_RS5_EEclIJEEENS_13__bind_returnIS7_NS_5tupleIJS9_S5_EEENSE_IJDpOT_EEEXsr22__is_valid_bind_returnIS7_SF_SJ_EE5valueEE4typeESI_(this=<unavailable>) at functional:2119 [opt]
    frame #7: 0x00000000005991ac CppTests`void std::__1::__invoke_void_return_wrapper<void>::__call<std::__1::__bind<void (litecore::repl::Replicator::*&)(litecore::websocket::CloseStatus), litecore::repl::Replicator*, litecore::websocket::CloseStatus&>&>(std::__1::__bind<void (litecore::repl::Replicator::*&)(litecore::websocket::CloseStatus), litecore::repl::Replicator*, litecore::websocket::CloseStatus&>&) [inlined] _ZNSt3__18__invokeIRNS_6__bindIRMN8litecore4repl10ReplicatorEFvNS2_9websocket11CloseStatusEEJPS4_RS6_EEEJEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSE_DpOSF_(__f=<unavailable>) at __functional_base:415 [opt]
    frame #8: 0x00000000005991ac CppTests`void std::__1::__invoke_void_return_wrapper<void>::__call<std::__1::__bind<void (__args=<unavailable>)(litecore::websocket::CloseStatus), litecore::repl::Replicator*, litecore::websocket::CloseStatus&>&>(std::__1::__bind<void (litecore::repl::Replicator::*&)(litecore::websocket::CloseStatus), litecore::repl::Replicator*, litecore::websocket::CloseStatus&>&) + 12 at __functional_base:440 [opt]
    frame #9: 0x00000000005dfc55 CppTests`litecore::ThreadedMailbox::performNextMessage() [inlined] std::__1::function<void ()>::operator()() const + 117 at functional:1789 [opt]
    frame #10: 0x00000000005dfc36 CppTests`litecore::ThreadedMailbox::performNextMessage(this=0x00000000009a6d40) + 86 at Actor.cc:256 [opt]
    frame #11: 0x00000000005dfb70 CppTests`litecore::Scheduler::task(this=<unavailable>, taskID=<unavailable>) + 176 at Actor.cc:83 [opt]
    frame #12: 0x00000000005e0101 CppTests`void* std::__1::__thread_proxy<std::__1::tuple<litecore::Scheduler::start()::$_0> >(void*) [inlined] litecore::Scheduler::start()::$_0::operator()() const + 97 at Actor.cc:51 [opt]
    frame #13: 0x00000000005e00f8 CppTests`void* std::__1::__thread_proxy<std::__1::tuple<litecore::Scheduler::start()::$_0> >(void*) [inlined] _ZNSt3__18__invokeIZN8litecore9Scheduler5startEvE3$_0JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOS4_DpOS5_ + 3 at __functional_base:415 [opt]
    frame #14: 0x00000000005e00f5 CppTests`void* std::__1::__thread_proxy<std::__1::tuple<litecore::Scheduler::start()::$_0> >(void*) [inlined] void std::__1::__thread_execute<litecore::Scheduler::start()::$_0>(std::__1::tuple<litecore::Scheduler::start()::$_0>&, std::__1::__tuple_indices<>) at thread:337 [opt]
    frame #15: 0x00000000005e00f5 CppTests`void* std::__1::__thread_proxy<std::__1::tuple<litecore::Scheduler::start()::$_0> >(__vp=0x0000000000933880) + 85 at thread:347 [opt]
    frame #16: 0x00007ffff6de06ba libpthread.so.0`start_thread + 202
    frame #17: 0x00007ffff610182d libc.so.6`clone + 109

**Comment by snej** [comment]
I haven't seen these, so they're likely due to a bug or different behavior in the thread-based Actor implementation (`ThreadedMailbox`). I can disable the GCD-based implementation and try to reproduce them.

**Comment by snej** [comment]
Hopefully this is fixed with commit 7c4c286c7f422731108cc4070821367a2e844401. ThreadedMailbox had different behavior than GCDMailbox, when a delayed call (from `enqueueAfter`) triggered after the Actor was finished. GCDMailbox would ignore it. ThreadedMailbox would originally crash due to dereferencing a deallocated ThreadedMailbox. I fixed it yesterday to retain the Actor and keep it and its mailbox alive, but it turns out having these delayed calls arrive after the replicator is finished confuses the replicator. Today with the above commit I made ThreadedMailbox's behavior match GCDMailbox's, i.e. any pending delayed calls are ignored when the Actor finishes.

**Comment by borrrden** [comment]
The crash is still in the same place in 41ec3d4

> \* thread 2: tid = 26437, 0x00000000005e0a4f CppTests \`litecore::actor::ThreadedMailbox::enqueue(this=0x0000000000000010, f=function<void ()> @ 0x00007ffff5bedd10)>) + 15 at ThreadedMailbox.cc:144, name = 'CppTests', stop reason = signal SIGSEGV: invalid address (fault address: 0xa0)
    frame #0: 0x00000000005e0a4f CppTests`litecore::actor::ThreadedMailbox::enqueue(this=0x0000000000000010, f=function<void ()> @ 0x00007ffff5bedd10)>) + 15 at ThreadedMailbox.cc:144 [opt]
   
         141 	
         142 	
         143        void ThreadedMailbox::enqueue(std::function<void()> f) {
      -> 144            retain(_actor);
         145            if (push(f)) {
         146                reschedule();
         147        }

**Comment by borrrden** [comment]
To be more specific, `_dbActor` inside the replicator is the one that is null.

    185 	
    186 	        // Clear connection() and notify the other agents to do the same:
    187 	        _connectionClosed();
    -> 188 	        _dbActor->connectionClosed();
    189 	        if (_pusher)
    190 	            _pusher->connectionClosed();
    191 	        if (_puller)

**Comment by borrrden** [comment]
It's starting to make sense what is happening now.  The connection closed callback, and replicator status changed callback are getting called out of order.  I'm running in a release build so all asserts are skipped, but when running in a debug build `assert(!connection())` gets tripped at Replicator.cc:139.  If this is skipped, this will set `_dbActor` at Replicator.cc:144 to `nullptr` and then the behavior will get hit above.

**Comment by snej** [comment]
I recommend running debug builds unless you're doing performance testing. They're a lot easier to troubleshoot.

**Comment by snej** [comment]
OK, thinking out loud … statusChanged isn't a callback (or rather, it's not an async actor message.) It's called by the Worker superclass at the end of handling an async event, if the actor changed its progress or activity level while handling the event.

The activity level is updated by computeActivityLevel. Replicator's implementation can only return kC4Stopped if its Connection is disconnected or closed, or null. So the implication is that when the crash happens, the connection is not null.

When the Connection closes/disconnects, Replicator's `_onClose` gets called and sets the connection reference to null.

So ... I think this is a race condition where the Connection has closed but the Replicator hasn't gotten the async notification yet. Instead it's handling some earlier event, and at the end of that it's updating its status and runs into this.

The problem is the disconnect between checking the 'live' status of the Connection, vs. the asynchronously-handled state of the `_connection` instance variable.

**Comment by snej** [comment]
Working on a fix....

**Comment by borrrden** [comment]
FYI I haven't seen this in a while

**Comment by snej** [comment]
Cool, my fix worked then :)
